### ISSUE TITLE
`retest` not recognising spec files as specs when modified.

### ISSUE THREAD

**Issue by gstamp** [AlexB52/retest#11]
Say I have some files with the following paths:

```
<project root>/app/lib/module/myfile.rb
<project root>/spec/module/myfile_spec.rb
```

retest will find the spec if I modify `myfile.rb` but If I modify `myfile_spec.rb` it reports: "Could not find a file test matching" (the wording of that feels a little off).

The behaviour I'm expecting is that retest realises this is a spec and just runs it directly.

**Comment by AlexB52** [comment]
Sorry I did not see a Github notification. That is a good point @gstamp. The behaviour and wording should be updated.

In the meantime, a workaround is to first save the `myfile.rb` which will run the spec `myfile_spec.rb` then you can modify your spec file `myfile_spec.rb`. 

The behaviour is that retest will rerun the last command run when no specs are found.
