### ISSUE TITLE
Allow configuring polling-based listener

### ISSUE THREAD

**Issue by DannyBen** [AlexB52/retest#125]
Right now, retest does not work in cases where the operating system requires a polling-based file change notification (for example, a Linux vagrant guest).

The `listen` gen has an [option for forcing polling](https://github.com/guard/listen#options) mechanism in the `Listen.to` method:

```ruby
force_polling: true     # Force the use of the polling adapter
```

Perhaps this can be exposed as an option to retest CLI? `retest --polling` or some other convention? (environment variable?)

I see this is the line that starts the `Listen.to` loop:

https://github.com/AlexB52/retest/blob/3bf9fc31850b7c9378300e18e645185e0b42dd3f/exe/retest#L36

(example rough fix in [this fork](https://github.com/DannyBen/retest/compare/main..dev))

**Comment by AlexB52** [comment]
Hi @DannyBen ,

This sounds like a good idea. 

I've stuck to flags so far and my gut feeling would be to add `--polling` for now. 
I'm not familiar with vagrant much but we could introduce the new flag while I find a way to test a vagrant box on GitHub actions and locally.

#### Default Latency

The polling method seems to work in pair with the `latency` option of `Listen` gem. When polling, the latency is `1.0` by default. Is your current fork of `Retest` works fine with the default latency?

I don't want to introduce latency option if we don't need to. It could be introduced later if required.

**Comment by DannyBen** [comment]
As for latency - I don't think there is a need to introduce another option. The default is fine.

As for testing - I don't think you should test that it works fine in vagrant, since that would mean you are actually testing the listen gem. The only test needed IMO, is to test that passing `--poll` passes the `force_polling: true` parameter to listen, sort of like that:

```ruby
expect(Listen).to receive(:to).with(force_polling: true).
subject.run "--poll"  # or whatever way we call the binary in specs
```

**Comment by AlexB52** [comment]
`--polling` flag introduced in release [1.8.0](https://github.com/AlexB52/retest/releases/tag/v1.8.0)

Let me know if this works as expected.

Cheers @DannyBen

**Comment by DannyBen** [comment]
Works like a charm! Thanks for the quick implementation.
